name: Deploy freshly built Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: 
          MONGO_CONNECTION = ${{ secrets.MONGO_CONNECTION }}
          JWT_SECRET_ARG = ${{ secrets.JWT_SECRET }}
          REDIS_HOST_ARG = ${{ secrets.REDIS_HOST }}
          REDIS_PORT_ARG=18278
          REDIS_USER_ARG=${{ secrets.REDIS_USER }}
          REDIS_PW_ARG=${{ secrets.REDIS_PW }}
          REDIS_DB_ARG=${{ secrets.REDIS_DB }}
        tags: stonks2moon/${{ steps.string.outputs.lowercase }}:${{ github.sha }}
